service_name: '2d984118-9ded-4194-875e-58838e475e0f'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url:  https://away-velvet-tape-comment.trycloudflare.com
  public_url:  https://away-velvet-tape-comment.trycloudflare.com
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: askdkas1223
